import * as DB from './db-v2.js';
import { extractQuote, quoteTotals, classifyItem } from './quote-parser.js';
import { analyzeTranscript } from './transcript-analyzer.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={companies:[],projects:[],visits:[],recordings:[],issues:[],causes:[],improvements:[],kpis:[],hardwares:[],softwares:[],tasks:[],quotations:[],quoteDraft:null,mediaRecorder:null,mediaStream:null,chunks:[],timer:null,startTime:null,currentBlob:null,recognition:null,audioCtx:null,analyser:null,meterRAF:null,whisperWorker:null,currentRecordingId:null};
const stores=DB.STORES;
const fmtMoney=v=>Number(String(v??'').replace(/[^0-9-]/g,'')||0).toLocaleString('ko-KR');
const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,'')||0);
const fmtBiz=v=>{const d=String(v||'').replace(/\D/g,'').slice(0,10);return d.length<=3?d:d.length<=5?`${d.slice(0,3)}-${d.slice(3)}`:`${d.slice(0,3)}-${d.slice(3,5)}-${d.slice(5)}`};
const fmtPhone=v=>{const d=String(v||'').replace(/\D/g,'').slice(0,11);if(d.startsWith('02'))return d.length<=2?d:d.length<=5?`${d.slice(0,2)}-${d.slice(2)}`:d.length<=9?`${d.slice(0,2)}-${d.slice(2,5)}-${d.slice(5)}`:`${d.slice(0,2)}-${d.slice(2,6)}-${d.slice(6)}`;return d.length<=3?d:d.length<=7?`${d.slice(0,3)}-${d.slice(3)}`:`${d.slice(0,3)}-${d.slice(3,d.length-4)}-${d.slice(-4)}`};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const toast=msg=>{const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),2400)};
const companyName=id=>state.companies.find(x=>x.id==id)?.company_name||`업체 ${id}`;
const projectLabel=id=>{const p=state.projects.find(x=>x.id==id);return p?`${companyName(p.company_id)} / ${p.project_year||''} ${p.project_title||''} (ID ${p.id})`:`프로젝트 ${id}`};
const visitLabel=id=>{const v=state.visits.find(x=>x.id==id);return v?`${v.visit_no}차 ${v.visit_date||''}`:`방문 ${id}`};
function formObj(form){const o=Object.fromEntries(new FormData(form).entries());if(o.id)o.id=Number(o.id);for(const k of ['company_id','project_id','visit_no','employee_count','qty'])if(k in o)o[k]=num(o[k]);for(const k of ['sales','total_budget','government_fund','self_cash','self_in_kind','amount'])if(k in o)o[k]=num(o[k]);return o}
function setForm(form,obj){for(const [k,v] of Object.entries(obj)){const el=form.elements[k];if(!el)continue;el.value=el.classList?.contains('money')?fmtMoney(v):v??'';}form.scrollIntoView({behavior:'smooth',block:'start'})}
function resetForm(id){const f=document.getElementById(id);f.reset();if(f.elements.id)f.elements.id.value='';if(id==='visitForm')f.elements.visit_date.value=new Date().toISOString().slice(0,10)}
function table(rows,cols,store){if(!rows.length)return '<div class="empty">등록된 데이터가 없습니다.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}<th>관리</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[2]?c[2](r[c[1]],r):esc(r[c[1]])}</td>`).join('')}<td><div class="row-actions"><button data-edit="${store}" data-id="${r.id}">수정</button><button class="danger" data-del="${store}" data-id="${r.id}">삭제</button></div></td></tr>`).join('')}</tbody></table></div>`}
async function load(){for(const s of stores)state[s]=await DB.all(s);renderAll();$('#saveStatus').textContent='브라우저 DB 정상'}
function options(){const co=state.companies.map(x=>`<option value="${x.id}">${esc(x.company_name)}</option>`).join('');$('#projectCompany').innerHTML='<option value="">업체 선택</option>'+co;const po=state.projects.map(x=>`<option value="${x.id}">${esc(projectLabel(x.id))}</option>`).join('');$('#visitProject').innerHTML='<option value="">프로젝트 선택</option>'+po;$$('.project-select').forEach(s=>s.innerHTML='<option value="">프로젝트 선택</option>'+po)}
function renderDashboard(){const metrics=[['업체',state.companies.length],['프로젝트',state.projects.length],['견적서',state.quotations.length],['현장방문',state.visits.length],['문제점',state.issues.length],['KPI',state.kpis.length]];$('#metricCards').innerHTML=metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#dashboardTable').innerHTML=table(state.projects,[['업체','company_id',v=>esc(companyName(v))],['연도','project_year'],['과제명','project_title'],['상태','status'],['총사업비','total_budget',v=>fmtMoney(v)]],'projects')}
function renderAll(){options();renderDashboard();$('#companyTable').innerHTML=table(state.companies,[['업체명','company_name'],['대표자','ceo_name'],['사업자등록번호','business_number'],['전화','phone'],['업종','industry_type']],'companies');$('#projectTable').innerHTML=table(state.projects,[['업체','company_id',v=>esc(companyName(v))],['연도','project_year'],['과제명','project_title'],['상태','status'],['총사업비','total_budget',v=>fmtMoney(v)]],'projects');$('#visitTable').innerHTML=table(state.visits,[['프로젝트','project_id',v=>esc(projectLabel(v))],['차수','visit_no'],['일자','visit_date'],['유형','visit_type'],['참석자','attendees']],'visits');$('#quotationTable').innerHTML=renderQuotations();$('#recordingTable').innerHTML=renderRecordings();$('#issueTable').innerHTML=table(state.issues,[['프로젝트','project_id',v=>esc(projectLabel(v))],['구분','category'],['문제','text'],['상태','status'],['근거','evidence']],'issues');$('#causeTable').innerHTML=table(state.causes,[['프로젝트','project_id',v=>esc(projectLabel(v))],['원인','text'],['상태','status'],['근거','evidence']],'causes');$('#improvementTable').innerHTML=table(state.improvements,[['프로젝트','project_id',v=>esc(projectLabel(v))],['개선과제','text'],['기대효과','expected_effect']],'improvements');$('#kpiTable').innerHTML=table(state.kpis,[['프로젝트','project_id',v=>esc(projectLabel(v))],['구분','category'],['KPI','name'],['기준','baseline'],['목표','target'],['단위','unit']],'kpis');$('#hardwareTable').innerHTML=table(state.hardwares,[['프로젝트','project_id',v=>esc(projectLabel(v))],['설비명','name'],['모델','model'],['수량','qty'],['금액','amount',v=>fmtMoney(v)]],'hardwares');$('#softwareTable').innerHTML=table(state.softwares,[['프로젝트','project_id',v=>esc(projectLabel(v))],['S/W','name'],['기능','functions'],['금액','amount',v=>fmtMoney(v)]],'softwares');bindRowActions()}
function renderQuotations(){if(!state.quotations.length)return '<div class="empty">등록된 견적서가 없습니다.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>프로젝트</th><th>파일명</th><th>총액</th><th>H/W</th><th>S/W</th><th>등록일</th><th>관리</th></tr></thead><tbody>${state.quotations.map(q=>`<tr><td>${esc(projectLabel(q.project_id))}</td><td>${esc(q.file_name||'수기 견적')}</td><td>${fmtMoney(q.total)}</td><td>${fmtMoney(q.hw_total)}</td><td>${fmtMoney(q.sw_total)}</td><td>${esc((q.updated_at||'').slice(0,10))}</td><td><div class="row-actions"><button data-edit-quote="${q.id}">수정</button><button class="danger" data-del-quote="${q.id}">삭제</button></div></td></tr>`).join('')}</tbody></table></div>`}
function renderRecordings(){if(!state.recordings.length)return '<div class="empty">저장된 녹음·전사가 없습니다.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>방문</th><th>저장일</th><th>전사 요약</th><th>관리</th></tr></thead><tbody>${state.recordings.map(r=>`<tr><td>${esc(visitLabel(r.visit_id))}</td><td>${esc((r.updated_at||r.created_at||'').slice(0,19).replace('T',' '))}</td><td>${esc((r.transcript||'').slice(0,120))}</td><td><div class="row-actions"><button data-play-rec="${r.id}">재생</button><button data-load-transcript="${r.id}">전사 수정</button><button class="danger" data-del="recordings" data-id="${r.id}">삭제</button></div></td></tr>`).join('')}</tbody></table></div>`}
function bindRowActions(){
  $$('[data-edit]').forEach(b=>b.onclick=async()=>{const store=b.dataset.edit,obj=await DB.get(store,+b.dataset.id);const map={companies:'companyForm',projects:'projectForm',visits:'visitForm',issues:'issueForm',causes:'causeForm',improvements:'improvementForm',kpis:'kpiForm',hardwares:'hardwareForm',softwares:'softwareForm'};const fid=map[store];if(!fid)return;const view=store==='companies'||store==='projects'?'companies':store==='visits'?'visits':['issues','causes','improvements'].includes(store)?'analysis':'kpi';document.querySelector(`[data-view="${view}"]`).click();setForm(document.getElementById(fid),obj);if(store==='projects'){budgetCheck();const q=state.quotations.find(x=>x.project_id===obj.id);if(q)loadQuoteDraft(q)}});
  $$('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('정말 삭제하시겠습니까? 삭제한 데이터는 되돌릴 수 없습니다.'))return;await DB.remove(b.dataset.del,+b.dataset.id);await load();toast('삭제했습니다.')});
  $$('[data-play-rec]').forEach(b=>b.onclick=async()=>{const r=await DB.get('recordings',+b.dataset.playRec);if(!r?.blob)return toast('이 녹음 원본은 현재 브라우저에 없습니다.');const a=$('#audioPreview');a.src=URL.createObjectURL(r.blob);a.classList.remove('hidden');a.play()});
  $$('[data-load-transcript]').forEach(b=>b.onclick=async()=>{const r=await DB.get('recordings',+b.dataset.loadTranscript);state.currentRecordingId=r.id;$('#transcriptBox').value=r.transcript||'';const v=state.visits.find(x=>x.id===r.visit_id);if(v)setForm($('#visitForm'),v);document.querySelector('[data-view="visits"]').click();toast('전사문을 불러왔습니다. 수정 후 저장할 수 있습니다.')});
  $$('[data-edit-quote]').forEach(b=>b.onclick=()=>{const q=state.quotations.find(x=>x.id===+b.dataset.editQuote);const p=state.projects.find(x=>x.id===q.project_id);if(p)setForm($('#projectForm'),p);loadQuoteDraft(q);document.querySelector('[data-view="companies"]').click()});
  $$('[data-del-quote]').forEach(b=>b.onclick=()=>deleteQuote(+b.dataset.delQuote));
}
async function deleteQuote(id){if(!confirm('견적서를 삭제하면 해당 견적서에서 자동 생성된 H/W·S/W 항목도 함께 삭제합니다. 계속할까요?'))return;for(const s of ['hardwares','softwares'])for(const row of state[s].filter(x=>x.quotation_id===id))await DB.remove(s,row.id);await DB.remove('quotations',id);if(state.quoteDraft?.id===id)clearQuoteDraft();await load();toast('견적서를 삭제했습니다.')}
function bindForms(){const configs=[['companyForm','companies'],['projectForm','projects'],['visitForm','visits'],['issueForm','issues'],['causeForm','causes'],['improvementForm','improvements'],['kpiForm','kpis'],['hardwareForm','hardwares'],['softwareForm','softwares']];for(const [id,store] of configs){const f=document.getElementById(id);f.onsubmit=async e=>{e.preventDefault();const o=formObj(f);if(store==='companies'){o.business_number=fmtBiz(o.business_number);o.phone=fmtPhone(o.phone)}if(store==='projects'){const sum=o.government_fund+o.self_cash+o.self_in_kind;if(o.total_budget&&sum!==o.total_budget&&!confirm(`사업비 합계가 일치하지 않습니다. 총사업비 ${fmtMoney(o.total_budget)}원 / 재원합계 ${fmtMoney(sum)}원\n그래도 저장할까요?`))return;const idOut=await DB.put(store,o);if(state.quoteDraft&&!state.quoteDraft.project_id){state.quoteDraft.project_id=idOut;await persistQuote(idOut)}resetForm(id);clearQuoteDraft();await load();toast('프로젝트와 연결정보를 저장했습니다.');continue}await DB.put(store,o);resetForm(id);await load();toast('저장했습니다.')}}$$('[data-reset]').forEach(b=>b.onclick=()=>{resetForm(b.dataset.reset);if(b.dataset.reset==='projectForm')clearQuoteDraft()});bindMoneyInputs();const cf=$('#companyForm');cf.elements.business_number.addEventListener('input',e=>e.target.value=fmtBiz(e.target.value));cf.elements.phone.addEventListener('input',e=>e.target.value=fmtPhone(e.target.value));['total_budget','government_fund','self_cash','self_in_kind'].forEach(n=>$('#projectForm').elements[n].addEventListener('input',budgetCheck))}
function bindMoneyInputs(){$$('.money').forEach(el=>{if(el.dataset.moneyBound)return;el.dataset.moneyBound='1';el.addEventListener('focus',()=>el.value=String(el.value).replace(/\D/g,''));el.addEventListener('blur',()=>el.value=el.value?fmtMoney(el.value):'')})}
function budgetCheck(){const f=$('#projectForm'),t=num(f.elements.total_budget.value),s=['government_fund','self_cash','self_in_kind'].reduce((a,n)=>a+num(f.elements[n].value),0),e=$('#budgetCheck');e.className=t===s?'budget-ok':'budget-bad';e.textContent=t===s?`✓ 재원 합계가 총사업비 ${fmtMoney(t)}원과 일치합니다.`:`⚠ 총사업비 ${fmtMoney(t)}원 / 재원합계 ${fmtMoney(s)}원 / 차이 ${fmtMoney(t-s)}원`}
function bindTabs(){$$('#tabs button').forEach(b=>b.onclick=()=>{$$('#tabs button').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active')})}
function setupQuote(){
  $('#parseQuote').onclick=async()=>{const file=$('#quoteFile').files?.[0];if(!file)return toast('견적서 파일을 선택해 주세요.');try{$('#quoteStatus').textContent='인식 중';$('#quoteProgress').textContent='견적서를 분석합니다.';const q=await extractQuote(file,msg=>$('#quoteProgress').textContent=msg);state.quoteDraft={id:null,project_id:num($('#projectForm').elements.id.value)||null,file_name:file.name,file_type:file.type,raw_text:q.raw_text,items:q.items,total:q.total,supply:q.supply,vat:q.vat};renderQuoteEditor();applyQuoteBudget();$('#quoteStatus').textContent='인식 완료';toast(`견적 항목 ${q.items.length}건을 인식했습니다.`)}catch(err){$('#quoteStatus').textContent='오류';$('#quoteProgress').textContent='견적서 인식 실패: '+err.message}};
  $('#addQuoteRow').onclick=()=>{ensureQuoteDraft();state.quoteDraft.items.push({name:'',category:'기타',model:'',qty:1,unit_price:0,amount:0,source_line:'수기 입력'});renderQuoteEditor()};
  $('#applyQuoteBudget').onclick=applyQuoteBudget;$('#saveQuote').onclick=async()=>{const pid=num($('#projectForm').elements.id.value);if(!pid)return toast('먼저 프로젝트를 저장하거나 기존 프로젝트를 수정으로 불러와 주세요.');await persistQuote(pid);await load();toast('견적서와 H/W·S/W 항목을 저장했습니다.')};
}
function ensureQuoteDraft(){if(!state.quoteDraft)state.quoteDraft={id:null,project_id:num($('#projectForm').elements.id.value)||null,file_name:'수기 견적',file_type:'manual',raw_text:'',items:[],total:0,supply:0,vat:0}}
function clearQuoteDraft(){state.quoteDraft=null;$('#quoteEditor').innerHTML='';$('#quoteTotals').innerHTML='';$('#quoteProgress').textContent='';$('#quoteStatus').textContent='대기';$('#quoteFile').value=''}
function loadQuoteDraft(q){state.quoteDraft=structuredClone(q);renderQuoteEditor();$('#quoteStatus').textContent='수정 중';$('#quoteProgress').textContent=q.file_name||'수기 견적'}
function renderQuoteEditor(){ensureQuoteDraft();const items=state.quoteDraft.items||[];if(!items.length){$('#quoteEditor').innerHTML='<div class="empty">인식된 항목이 없습니다. 수기 항목 추가를 눌러 입력할 수 있습니다.</div>';renderQuoteTotals();return}$('#quoteEditor').innerHTML=`<div class="table-wrap"><table class="data-table quote-table"><thead><tr><th>구분</th><th>품목명</th><th>모델/사양</th><th>수량</th><th>단가</th><th>금액</th><th>삭제</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td><select data-qi="${i}" data-qf="category"><option ${x.category==='H/W'?'selected':''}>H/W</option><option ${x.category==='S/W'?'selected':''}>S/W</option><option ${x.category==='기타'?'selected':''}>기타</option></select></td><td><input data-qi="${i}" data-qf="name" value="${esc(x.name)}"/></td><td><input data-qi="${i}" data-qf="model" value="${esc(x.model||'')}"/></td><td><input type="number" min="1" data-qi="${i}" data-qf="qty" value="${num(x.qty)||1}"/></td><td><input class="quote-money" data-qi="${i}" data-qf="unit_price" value="${fmtMoney(x.unit_price)}"/></td><td><input class="quote-money" data-qi="${i}" data-qf="amount" value="${fmtMoney(x.amount)}"/></td><td><button class="danger" data-qdel="${i}">삭제</button></td></tr>`).join('')}</tbody></table></div>`;$$('[data-qi]').forEach(el=>el.onchange=()=>{const i=+el.dataset.qi,f=el.dataset.qf;state.quoteDraft.items[i][f]=['qty','unit_price','amount'].includes(f)?num(el.value):el.value;if(f==='name'&&state.quoteDraft.items[i].category==='기타')state.quoteDraft.items[i].category=classifyItem(el.value);renderQuoteTotals()});$$('.quote-money').forEach(el=>{el.onfocus=()=>el.value=String(el.value).replace(/\D/g,'');el.onblur=()=>{el.value=fmtMoney(el.value);el.dispatchEvent(new Event('change'))}});$$('[data-qdel]').forEach(b=>b.onclick=()=>{state.quoteDraft.items.splice(+b.dataset.qdel,1);renderQuoteEditor()});renderQuoteTotals()}
function renderQuoteTotals(){ensureQuoteDraft();const t=quoteTotals(state.quoteDraft.items);state.quoteDraft.total=t.total;state.quoteDraft.hw_total=t.hw;state.quoteDraft.sw_total=t.sw;state.quoteDraft.other_total=t.other;$('#quoteTotals').innerHTML=`<div class="quote-summary"><span>H/W <strong>${fmtMoney(t.hw)}원</strong></span><span>S/W <strong>${fmtMoney(t.sw)}원</strong></span><span>기타 <strong>${fmtMoney(t.other)}원</strong></span><span>합계 <strong>${fmtMoney(t.total)}원</strong></span></div>`}
function applyQuoteBudget(){ensureQuoteDraft();renderQuoteTotals();const total=state.quoteDraft.total||0,f=$('#projectForm');f.elements.total_budget.value=fmtMoney(total);if($('#fundingRule').value==='60-20-20'){f.elements.government_fund.value=fmtMoney(Math.round(total*.6));f.elements.self_cash.value=fmtMoney(Math.round(total*.2));f.elements.self_in_kind.value=fmtMoney(total-Math.round(total*.6)-Math.round(total*.2))}budgetCheck()}
async function persistQuote(projectId){ensureQuoteDraft();renderQuoteTotals();const payload={...state.quoteDraft,project_id:projectId};const quoteId=await DB.put('quotations',payload);payload.id=quoteId;state.quoteDraft=payload;for(const s of ['hardwares','softwares'])for(const row of state[s].filter(x=>x.quotation_id===quoteId))await DB.remove(s,row.id);for(const item of payload.items){if(item.category==='H/W')await DB.put('hardwares',{project_id:projectId,name:item.name,model:item.model||'',qty:num(item.qty)||1,amount:num(item.amount),location:'',quotation_id:quoteId,source:'quotation'});if(item.category==='S/W')await DB.put('softwares',{project_id:projectId,name:item.name,functions:item.model||item.source_line||'',amount:num(item.amount),quotation_id:quoteId,source:'quotation'})}const p=await DB.get('projects',projectId);if(p){const total=payload.total||0;p.total_budget=total;if($('#fundingRule').value==='60-20-20'){p.government_fund=Math.round(total*.6);p.self_cash=Math.round(total*.2);p.self_in_kind=total-p.government_fund-p.self_cash}await DB.put('projects',p)}return quoteId}
async function setupRecording(){$('#startRec').onclick=startRecording;$('#stopRec').onclick=stopRecording;$('#saveTranscript').onclick=saveTranscript;$('#analyzeAll').onclick=analyzeAndApply;$('#localWhisper').onclick=transcribeLocal}
async function startRecording(){if(!$('#visitForm').elements.id.value){toast('먼저 방문내용을 저장하거나 기존 방문을 수정으로 불러와 주세요.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.mediaStream=stream;state.chunks=[];state.currentBlob=null;const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'';state.mediaRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.mediaRecorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.mediaRecorder.onstop=()=>{state.currentBlob=new Blob(state.chunks,{type:state.mediaRecorder.mimeType||'audio/webm'});const a=$('#audioPreview');a.src=URL.createObjectURL(state.currentBlob);a.classList.remove('hidden');$('#localWhisper').disabled=false};state.mediaRecorder.start(1000);startMeter(stream);startTimer();startBrowserSpeech();$('#startRec').disabled=true;$('#stopRec').disabled=false;$('#recStatus').textContent='녹음 중';$('#micInfo').textContent='마이크 입력 중'}catch(err){$('#sttMessage').textContent='마이크를 열 수 없습니다: '+err.message;toast('브라우저의 마이크 권한을 확인해 주세요.')}}
function stopRecording(){if(state.mediaRecorder&&state.mediaRecorder.state!=='inactive')state.mediaRecorder.stop();state.mediaStream?.getTracks().forEach(t=>t.stop());stopBrowserSpeech();stopTimer();cancelAnimationFrame(state.meterRAF);state.audioCtx?.close();$('#meterFill').style.width='0%';$('#startRec').disabled=false;$('#stopRec').disabled=true;$('#recStatus').textContent='녹음 완료';$('#micInfo').textContent='마이크 종료'}
function startTimer(){state.startTime=Date.now();state.timer=setInterval(()=>{const s=Math.floor((Date.now()-state.startTime)/1000);$('#timer').textContent=[Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')},250)}
function stopTimer(){clearInterval(state.timer)}
function startMeter(stream){state.audioCtx=new AudioContext();const src=state.audioCtx.createMediaStreamSource(stream);state.analyser=state.audioCtx.createAnalyser();state.analyser.fftSize=256;src.connect(state.analyser);const arr=new Uint8Array(state.analyser.frequencyBinCount);const tick=()=>{state.analyser.getByteFrequencyData(arr);const avg=arr.reduce((a,b)=>a+b,0)/arr.length;$('#meterFill').style.width=`${Math.min(100,avg*1.6)}%`;state.meterRAF=requestAnimationFrame(tick)};tick()}
function startBrowserSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#sttMessage').textContent='이 브라우저는 실시간 보조 전사를 지원하지 않습니다. 녹음 후 로컬 Whisper 전사를 이용하세요.';return}const r=new SR();r.lang='ko-KR';r.continuous=true;r.interimResults=true;r.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+'\n';else interim+=t}if(final)$('#transcriptBox').value+=final;$('#sttMessage').textContent=interim?`인식 중: ${interim}`:'실시간 보조 전사 중'};r.onerror=()=>{};r.onend=()=>{if(state.mediaRecorder?.state==='recording')try{r.start()}catch{}};state.recognition=r;try{r.start()}catch{}}
function stopBrowserSpeech(){try{state.recognition?.stop()}catch{}state.recognition=null}
async function saveTranscript(){const visitId=num($('#visitForm').elements.id.value);if(!visitId)return toast('방문기록을 먼저 선택해 주세요.');const transcript=$('#transcriptBox').value.trim();if(!transcript&&!state.currentBlob)return toast('저장할 녹음 또는 전사 내용이 없습니다.');let row=state.currentRecordingId?await DB.get('recordings',state.currentRecordingId):null;row={...(row||{}),visit_id:visitId,project_id:num($('#visitForm').elements.project_id.value),transcript,blob:state.currentBlob||row?.blob||null,created_at:row?.created_at||new Date().toISOString()};const id=await DB.put('recordings',row);state.currentRecordingId=id;await load();toast('전사문을 저장/수정했습니다.')}
async function transcribeLocal(){if(!state.currentBlob)return toast('먼저 녹음을 완료해 주세요.');$('#sttMessage').textContent='녹음 파일을 Whisper용 음성으로 변환 중입니다.';try{const audio=await blobTo16kFloat(state.currentBlob);if(!state.whisperWorker){state.whisperWorker=new Worker('./whisper-worker.js',{type:'module'});state.whisperWorker.onmessage=e=>{const m=e.data||{};if(m.type==='status')$('#sttMessage').textContent=m.message;if(m.type==='progress')$('#sttMessage').textContent=`Whisper 모델 준비 ${Math.round(m.progress||0)}%`;if(m.type==='result'){$('#transcriptBox').value=m.text||'';$('#sttMessage').textContent='고정밀 전사가 완료되었습니다. 내용을 확인·수정한 뒤 저장하세요.'}if(m.type==='error')$('#sttMessage').textContent='로컬 Whisper 오류: '+m.message}}state.whisperWorker.postMessage({type:'transcribe',audio},[audio.buffer])}catch(err){$('#sttMessage').textContent='전사 준비 오류: '+err.message}}
async function blobTo16kFloat(blob){const ab=await blob.arrayBuffer(),ctx=new AudioContext();const decoded=await ctx.decodeAudioData(ab.slice(0));const mono=decoded.getChannelData(0);const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000);const buf=offline.createBuffer(1,mono.length,decoded.sampleRate);buf.copyToChannel(mono,0);const src=offline.createBufferSource();src.buffer=buf;src.connect(offline.destination);src.start();const rendered=await offline.startRendering();await ctx.close();return new Float32Array(rendered.getChannelData(0))}
async function analyzeAndApply(){const visitId=num($('#visitForm').elements.id.value),projectId=num($('#visitForm').elements.project_id.value),text=$('#transcriptBox').value.trim();if(!visitId||!projectId)return toast('방문기록과 프로젝트를 먼저 선택해 주세요.');if(text.length<10)return toast('분석할 전사 내용이 부족합니다.');const a=analyzeTranscript(text);const visit=await DB.get('visits',visitId);visit.purpose=a.purpose;visit.summary=a.summary?`• ${a.summary}`:'';visit.memo=[visit.memo,a.memo].filter(Boolean).join('\n');await DB.put('visits',visit);for(const s of ['issues','causes','improvements','kpis','hardwares','softwares'])for(const row of state[s].filter(x=>x.source==='transcript-auto'&&x.source_visit_id===visitId))await DB.remove(s,row.id);for(const x of a.issues)await DB.put('issues',{project_id:projectId,...x,source:'transcript-auto',source_visit_id:visitId});for(const x of a.causes)await DB.put('causes',{project_id:projectId,...x,source:'transcript-auto',source_visit_id:visitId});for(const x of a.improvements)await DB.put('improvements',{project_id:projectId,...x,source:'transcript-auto',source_visit_id:visitId});for(const x of a.kpis)await DB.put('kpis',{project_id:projectId,...x,source:'transcript-auto',source_visit_id:visitId});for(const x of a.hardwares)await DB.put('hardwares',{project_id:projectId,name:x.name,model:'',qty:1,amount:0,location:'',source:'transcript-auto',source_visit_id:visitId,evidence:x.evidence});for(const x of a.softwares)await DB.put('softwares',{project_id:projectId,name:x.name,functions:x.functions,amount:0,source:'transcript-auto',source_visit_id:visitId,evidence:x.evidence});setForm($('#visitForm'),visit);$('#analysisPreview').classList.remove('hidden');$('#analysisPreview').innerHTML=`<strong>자동분석 완료</strong><div class="auto-counts"><span>문제 ${a.issues.length}</span><span>원인 ${a.causes.length}</span><span>개선과제 ${a.improvements.length}</span><span>KPI ${a.kpis.length}</span><span>H/W ${a.hardwares.length}</span><span>S/W ${a.softwares.length}</span></div><p>${esc(a.memo||'녹취 근거 항목을 각 탭에 자동 입력했습니다.')}</p>`;await load();toast('방문내용과 다른 탭에 자동 입력했습니다. 모두 수정·삭제할 수 있습니다.')}
function setupBackup(){$('#exportJson').onclick=async()=>{const data=await DB.exportData();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`smart_coord_backup_${new Date().toISOString().slice(0,10).replaceAll('-','')}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importJson').onclick=async()=>{const f=$('#importFile').files?.[0];if(!f)return toast('백업 파일을 선택해 주세요.');if(!confirm('현재 브라우저 DB를 백업 파일 내용으로 교체합니다. 계속할까요?'))return;await DB.importData(JSON.parse(await f.text()));await load();toast('복원이 완료되었습니다.')}}
async function boot(){bindTabs();bindForms();setupQuote();await setupRecording();setupBackup();resetForm('visitForm');await load();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
boot().catch(err=>{$('#saveStatus').textContent='초기화 오류';console.error(err)});
