import * as DB from './db.js';
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const state={companies:[],projects:[],visits:[],recordings:[],issues:[],causes:[],improvements:[],kpis:[],hardwares:[],softwares:[],tasks:[],mediaRecorder:null,mediaStream:null,chunks:[],timer:null,startTime:null,currentBlob:null,recognition:null,audioCtx:null,analyser:null,meterRAF:null,whisperWorker:null};
const stores=DB.STORES;
const fmtMoney=v=>Number(String(v??'').replace(/[^0-9-]/g,'' )||0).toLocaleString('ko-KR');
const numberValue=v=>Number(String(v??'').replace(/[^0-9-]/g,'' )||0);
const fmtBiz=v=>{const d=String(v||'').replace(/\D/g,'').slice(0,10);return d.length<=3?d:d.length<=5?`${d.slice(0,3)}-${d.slice(3)}`:`${d.slice(0,3)}-${d.slice(3,5)}-${d.slice(5)}`};
const fmtPhone=v=>{const d=String(v||'').replace(/\D/g,'').slice(0,11);if(d.startsWith('02'))return d.length<=2?d:d.length<=5?`${d.slice(0,2)}-${d.slice(2)}`:d.length<=9?`${d.slice(0,2)}-${d.slice(2,5)}-${d.slice(5)}`:`${d.slice(0,2)}-${d.slice(2,6)}-${d.slice(6)}`;return d.length<=3?d:d.length<=7?`${d.slice(0,3)}-${d.slice(3)}`:`${d.slice(0,3)}-${d.slice(3,d.length-4)}-${d.slice(-4)}`};
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),2200)}
function formObj(form){const o=Object.fromEntries(new FormData(form).entries());if(o.id)o.id=Number(o.id);for(const k of ['company_id','project_id','visit_no','employee_count','qty'])if(k in o)o[k]=numberValue(o[k]);for(const k of ['sales','total_budget','government_fund','self_cash','self_in_kind','amount'])if(k in o)o[k]=numberValue(o[k]);return o}
function setForm(form,obj){for(const [k,v] of Object.entries(obj)){const el=form.elements[k];if(!el)continue;el.value=(el.classList?.contains('money'))?fmtMoney(v):v??'';}form.scrollIntoView({behavior:'smooth',block:'start'});}
function resetForm(id){const f=document.getElementById(id);f.reset();if(f.elements.id)f.elements.id.value='';if(id==='visitForm')f.elements.visit_date.value=new Date().toISOString().slice(0,10);}
function table(rows,cols,store){if(!rows.length)return '<div class="empty">등록된 데이터가 없습니다.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}<th>관리</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[2]?c[2](r[c[1]],r):escapeHtml(String(r[c[1]]??''))}</td>`).join('')}<td><div class="row-actions"><button data-edit="${store}" data-id="${r.id}">수정</button><button class="danger" data-del="${store}" data-id="${r.id}">삭제</button></div></td></tr>`).join('')}</tbody></table></div>`}
function escapeHtml(s){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function companyName(id){return state.companies.find(x=>x.id==id)?.company_name||`업체 ${id}`}
function projectLabel(id){const p=state.projects.find(x=>x.id==id);return p?`${companyName(p.company_id)} / ${p.project_year||''} ${p.project_title||''} (ID ${p.id})`:`프로젝트 ${id}`}
function visitLabel(id){const v=state.visits.find(x=>x.id==id);return v?`${v.visit_no}차 ${v.visit_date||''}`:`방문 ${id}`}
async function load(){for(const s of stores)state[s]=await DB.all(s);renderAll();$('#saveStatus').textContent='브라우저 DB 저장 중';setTimeout(()=>$('#saveStatus').textContent='브라우저 DB 정상',400)}
function options(){const co=state.companies.map(x=>`<option value="${x.id}">${escapeHtml(x.company_name)}</option>`).join('');$('#projectCompany').innerHTML='<option value="">업체 선택</option>'+co;const po=state.projects.map(x=>`<option value="${x.id}">${escapeHtml(projectLabel(x.id))}</option>`).join('');$('#visitProject').innerHTML='<option value="">프로젝트 선택</option>'+po;$$('.project-select').forEach(s=>s.innerHTML='<option value="">프로젝트 선택</option>'+po)}
function renderDashboard(){const metrics=[['업체',state.companies.length],['프로젝트',state.projects.length],['현장방문',state.visits.length],['문제점',state.issues.length],['KPI',state.kpis.length]];$('#metricCards').innerHTML=metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#dashboardTable').innerHTML=table(state.projects,[['업체','company_id',(v)=>escapeHtml(companyName(v))],['연도','project_year'],['과제명','project_title'],['상태','status'],['총사업비','total_budget',(v)=>fmtMoney(v)]],'projects')}
function renderAll(){options();renderDashboard();$('#companyTable').innerHTML=table(state.companies,[['업체명','company_name'],['대표자','ceo_name'],['사업자등록번호','business_number'],['전화','phone'],['업종','industry_type']],'companies');$('#projectTable').innerHTML=table(state.projects,[['업체','company_id',(v)=>escapeHtml(companyName(v))],['연도','project_year'],['과제명','project_title'],['상태','status'],['총사업비','total_budget',(v)=>fmtMoney(v)]],'projects');$('#visitTable').innerHTML=table(state.visits,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['차수','visit_no'],['일자','visit_date'],['유형','visit_type'],['참석자','attendees']],'visits');$('#recordingTable').innerHTML=renderRecordings();$('#issueTable').innerHTML=table(state.issues,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['구분','category'],['문제','text'],['상태','status'],['근거','evidence']],'issues');$('#causeTable').innerHTML=table(state.causes,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['원인','text'],['상태','status'],['근거','evidence']],'causes');$('#improvementTable').innerHTML=table(state.improvements,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['개선과제','text'],['기대효과','expected_effect']],'improvements');$('#kpiTable').innerHTML=table(state.kpis,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['구분','category'],['KPI','name'],['기준','baseline'],['목표','target'],['단위','unit']],'kpis');$('#hardwareTable').innerHTML=table(state.hardwares,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['설비명','name'],['모델','model'],['수량','qty'],['금액','amount',(v)=>fmtMoney(v)]],'hardwares');$('#softwareTable').innerHTML=table(state.softwares,[['프로젝트','project_id',(v)=>escapeHtml(projectLabel(v))],['S/W','name'],['기능','functions'],['금액','amount',(v)=>fmtMoney(v)]],'softwares');bindRowActions()}
function renderRecordings(){if(!state.recordings.length)return '<div class="empty">저장된 녹음·전사가 없습니다.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>방문</th><th>저장일</th><th>전사 요약</th><th>관리</th></tr></thead><tbody>${state.recordings.map(r=>`<tr><td>${escapeHtml(visitLabel(r.visit_id))}</td><td>${escapeHtml((r.created_at||'').slice(0,19).replace('T',' '))}</td><td>${escapeHtml((r.transcript||'').slice(0,100))}</td><td><div class="row-actions"><button data-play-rec="${r.id}">재생</button><button data-load-transcript="${r.id}">전사 불러오기</button><button class="danger" data-del="recordings" data-id="${r.id}">삭제</button></div></td></tr>`).join('')}</tbody></table></div>`}
function bindRowActions(){$$('[data-edit]').forEach(b=>b.onclick=async()=>{const store=b.dataset.edit,id=+b.dataset.id,obj=await DB.get(store,id);const map={companies:'companyForm',projects:'projectForm',visits:'visitForm',issues:'issueForm',causes:'causeForm',improvements:'improvementForm',kpis:'kpiForm',hardwares:'hardwareForm',softwares:'softwareForm'};const fid=map[store];if(fid){document.querySelector(`[data-view="${store==='companies'||store==='projects'?'companies':store==='visits'?'visits':store==='issues'||store==='causes'||store==='improvements'?'analysis':'kpi'}"]`).click();setForm(document.getElementById(fid),obj)}});$$('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('정말 삭제하시겠습니까? 삭제한 데이터는 되돌릴 수 없습니다.'))return;await DB.remove(b.dataset.del,+b.dataset.id);await load();toast('삭제했습니다.')});$$('[data-play-rec]').forEach(b=>b.onclick=async()=>{const r=await DB.get('recordings',+b.dataset.playRec);if(!r?.blob)return toast('이 녹음 원본은 현재 브라우저에 없습니다.');const a=$('#audioPreview');a.src=URL.createObjectURL(r.blob);a.classList.remove('hidden');a.play()});$$('[data-load-transcript]').forEach(b=>b.onclick=async()=>{const r=await DB.get('recordings',+b.dataset.loadTranscript);$('#transcriptBox').value=r?.transcript||'';document.querySelector('[data-view="visits"]').click();toast('전사문을 불러왔습니다.')})}
function bindForms(){const configs=[['companyForm','companies'],['projectForm','projects'],['visitForm','visits'],['issueForm','issues'],['causeForm','causes'],['improvementForm','improvements'],['kpiForm','kpis'],['hardwareForm','hardwares'],['softwareForm','softwares']];for(const [id,store] of configs){const f=document.getElementById(id);f.onsubmit=async e=>{e.preventDefault();const o=formObj(f);if(store==='companies'){o.business_number=fmtBiz(o.business_number);o.phone=fmtPhone(o.phone)}if(store==='projects'){const sum=o.government_fund+o.self_cash+o.self_in_kind;if(o.total_budget&&sum!==o.total_budget){if(!confirm(`사업비 합계가 일치하지 않습니다. 총사업비 ${fmtMoney(o.total_budget)}원 / 재원합계 ${fmtMoney(sum)}원\n그래도 저장할까요?`))return;}}await DB.put(store,o);resetForm(id);await load();toast('저장했습니다.')}}$$('[data-reset]').forEach(b=>b.onclick=()=>resetForm(b.dataset.reset));$$('.money').forEach(el=>{el.addEventListener('focus',()=>el.value=String(el.value).replace(/\D/g,''));el.addEventListener('blur',()=>el.value=el.value?fmtMoney(el.value):'')});const cf=$('#companyForm');cf.elements.business_number.addEventListener('input',e=>e.target.value=fmtBiz(e.target.value));cf.elements.phone.addEventListener('input',e=>e.target.value=fmtPhone(e.target.value));['total_budget','government_fund','self_cash','self_in_kind'].forEach(n=>$('#projectForm').elements[n].addEventListener('input',budgetCheck));}
function budgetCheck(){const f=$('#projectForm'),t=numberValue(f.elements.total_budget.value),s=['government_fund','self_cash','self_in_kind'].reduce((a,n)=>a+numberValue(f.elements[n].value),0);const e=$('#budgetCheck');e.className=t===s?'budget-ok':'budget-bad';e.textContent=t===s?`✓ 재원 합계가 총사업비 ${fmtMoney(t)}원과 일치합니다.`:`⚠ 총사업비 ${fmtMoney(t)}원 / 재원합계 ${fmtMoney(s)}원 / 차이 ${fmtMoney(t-s)}원`;}
function bindTabs(){$$('#tabs button').forEach(b=>b.onclick=()=>{$$('#tabs button').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active')})}
function today(){const d=new Date().toISOString().slice(0,10);$('#visitForm').elements.visit_date.value=d}
async function setupRecording(){$('#startRec').onclick=startRecording;$('#stopRec').onclick=stopRecording;$('#saveTranscript').onclick=saveTranscript;$('#applyTranscript').onclick=applyTranscript;$('#localWhisper').onclick=transcribeLocal;}
async function startRecording(){
  if(!$('#visitForm').elements.id.value){toast('먼저 방문내용을 저장하거나 방문 이력을 수정으로 불러와 주세요.');return;}
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.mediaStream=stream;state.chunks=[];const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'';state.mediaRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.mediaRecorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.mediaRecorder.onstop=()=>{state.currentBlob=new Blob(state.chunks,{type:state.mediaRecorder.mimeType||'audio/webm'});const a=$('#audioPreview');a.src=URL.createObjectURL(state.currentBlob);a.classList.remove('hidden');$('#localWhisper').disabled=false;};state.mediaRecorder.start(1000);startMeter(stream);startTimer();startBrowserSpeech();$('#startRec').disabled=true;$('#stopRec').disabled=false;$('#recStatus').textContent='녹음 중';$('#recStatus').className='status-pill';$('#micInfo').textContent='마이크 입력 중';}
  catch(err){$('#sttMessage').textContent='마이크를 열 수 없습니다: '+err.message;toast('브라우저의 마이크 권한을 확인해 주세요.')}
}
function stopRecording(){if(state.mediaRecorder&&state.mediaRecorder.state!=='inactive')state.mediaRecorder.stop();state.mediaStream?.getTracks().forEach(t=>t.stop());stopBrowserSpeech();stopTimer();cancelAnimationFrame(state.meterRAF);state.audioCtx?.close();$('#meterFill').style.width='0%';$('#startRec').disabled=false;$('#stopRec').disabled=true;$('#recStatus').textContent='녹음 완료';$('#recStatus').className='status-pill neutral';$('#micInfo').textContent='마이크 종료';}
function startTimer(){state.startTime=Date.now();state.timer=setInterval(()=>{const s=Math.floor((Date.now()-state.startTime)/1000);$('#timer').textContent=[Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')},250)}
function stopTimer(){clearInterval(state.timer)}
function startMeter(stream){state.audioCtx=new AudioContext();const src=state.audioCtx.createMediaStreamSource(stream);state.analyser=state.audioCtx.createAnalyser();state.analyser.fftSize=256;src.connect(state.analyser);const arr=new Uint8Array(state.analyser.frequencyBinCount);const tick=()=>{state.analyser.getByteFrequencyData(arr);const avg=arr.reduce((a,b)=>a+b,0)/arr.length;$('#meterFill').style.width=Math.min(100,avg*1.7)+'%';state.meterRAF=requestAnimationFrame(tick)};tick()}
function startBrowserSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#sttMessage').textContent='이 브라우저는 실시간 보조 전사를 지원하지 않습니다. 녹음 후 로컬 Whisper 고정밀 전사를 사용하세요.';return}try{const r=new SR();r.lang='ko-KR';r.continuous=true;r.interimResults=true;let committed=$('#transcriptBox').value.trim();r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)committed+=(committed?' ':'')+t.trim();else interim+=t}$('#transcriptBox').value=(committed+(interim?'\n[인식 중] '+interim:'')).trim()};r.onerror=e=>{$('#sttMessage').textContent='실시간 보조 전사 상태: '+e.error};r.onend=()=>{if(state.mediaRecorder?.state==='recording')try{r.start()}catch{}};r.start();state.recognition=r;$('#sttMessage').textContent='실시간 보조 전사 사용 중. 최종 문서용 전사는 녹음 후 로컬 Whisper를 권장합니다.'}catch(err){$('#sttMessage').textContent='실시간 보조 전사를 시작하지 못했습니다: '+err.message}}
function stopBrowserSpeech(){try{state.recognition?.stop()}catch{}state.recognition=null}
async function saveTranscript(){const visitId=numberValue($('#visitForm').elements.id.value);if(!visitId)return toast('방문을 먼저 저장해 주세요.');const transcript=$('#transcriptBox').value.trim();if(!transcript&&!state.currentBlob)return toast('저장할 녹음 또는 전사문이 없습니다.');await DB.put('recordings',{visit_id:visitId,project_id:numberValue($('#visitForm').elements.project_id.value),transcript,blob:state.currentBlob,created_at:new Date().toISOString()});await load();toast('녹음·전사 데이터를 저장했습니다.')}
function applyTranscript(){const text=$('#transcriptBox').value.trim();if(!text)return toast('전사문이 없습니다.');const f=$('#visitForm');if(!f.elements.summary.value)f.elements.summary.value=text;else f.elements.summary.value+='\n'+text;const facts=analyzeText(text);if(!f.elements.memo.value&&facts.questions.length)f.elements.memo.value='추가 확인 필요:\n- '+facts.questions.join('\n- ');toast('전사문을 방문내용에 반영했습니다. 저장 전에 검토해 주세요.')}
function analyzeText(text){const q=[];if(!/(불량률|불량.*%|퍼센트)/.test(text))q.push('현재 불량률과 목표 불량률을 확인해야 합니다.');if(!/(목표.*생산|생산.*목표)/.test(text))q.push('구축 후 목표 생산량을 확인해야 합니다.');if(!/(PLC|통신|RS-?485|이더넷|Ethernet|OPC)/i.test(text))q.push('설비의 통신/데이터 수집 가능 여부를 확인해야 합니다.');return{questions:q}}
async function transcribeLocal(){if(!state.currentBlob)return toast('먼저 녹음을 완료해 주세요.');$('#localWhisper').disabled=true;$('#sttMessage').textContent='오디오를 로컬 Whisper 입력으로 변환 중입니다.';try{const ab=await state.currentBlob.arrayBuffer();const ac=new AudioContext();const decoded=await ac.decodeAudioData(ab.slice(0));const targetRate=16000;const off=new OfflineAudioContext(1,Math.ceil(decoded.duration*targetRate),targetRate);const src=off.createBufferSource();src.buffer=decoded;src.connect(off.destination);src.start();const rendered=await off.startRendering();const audio=new Float32Array(rendered.getChannelData(0));await ac.close();if(!state.whisperWorker){state.whisperWorker=new Worker('./whisper-worker.js',{type:'module'});state.whisperWorker.onmessage=e=>{const d=e.data;if(d.type==='status')$('#sttMessage').textContent=d.message;if(d.type==='progress')$('#sttMessage').textContent=`모델 다운로드/준비 ${Math.round(d.progress||0)}%`;if(d.type==='result'){if(d.text)$('#transcriptBox').value=d.text;$('#sttMessage').textContent='로컬 Whisper 전사가 완료되었습니다.';$('#localWhisper').disabled=false}if(d.type==='error'){console.error(d.message);$('#sttMessage').textContent='로컬 Whisper 오류: '+d.message;$('#localWhisper').disabled=false}}}state.whisperWorker.postMessage({type:'transcribe',audio},[audio.buffer]);}
  catch(err){$('#sttMessage').textContent='오디오 변환/전사 준비 오류: '+err.message;$('#localWhisper').disabled=false}}
async function exportJson(){const data=await DB.exportData();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`smart_coord_backup_${new Date().toISOString().slice(0,10).replaceAll('-','')}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importJson(){const f=$('#importFile').files[0];if(!f)return toast('백업 JSON 파일을 선택해 주세요.');if(!confirm('현재 브라우저 DB를 지우고 선택한 백업으로 복원합니다. 계속할까요?'))return;const data=JSON.parse(await f.text());await DB.importData(data);await load();toast('백업을 복원했습니다.')}
function bindBackup(){$('#exportJson').onclick=exportJson;$('#importJson').onclick=importJson}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
bindTabs();bindForms();setupRecording();bindBackup();today();load();
